name: CI

on: [push]

jobs:
  send:
    runs-on: ubuntu-latest
    name: Send Test Text To Slack
    steps:
    - name: Send Text
      uses: devtk0582/slack-post-action@v1.1
      with:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MESSAGE: "GO TEST" 
